FROM squidfunk/mkdocs-material:9.5.0

# Install all required Python packages
RUN pip install --no-cache-dir \
    mkdocs-drawio \
    mkdocs-minify-plugin \
    mkdocs-git-revision-date-localized-plugin \
    mkdocs-awesome-pages-plugin \
    mkdocs-material \
    mkdocs-mermaid2-plugin \
    mkdocs-table-reader-plugin

# Set working directory
WORKDIR /docs

# Expose MkDocs port
EXPOSE 8001

# Default command
CMD [ "serve", "--dev-addr=0.0.0.0:8001"]