FROM node:20-alpine

# Install markdownlint globally
RUN npm install -g --no-audit --no-fund \
    markdownlint-cli@0.41.0

# Set working directory
WORKDIR /workspace

# Default command
ENTRYPOINT ["markdownlint"]

CMD ["--help"]